# Generated by Django 5.2.1 on 2025-06-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresse',
            name='loc',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='adresse',
            name='number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='adresse',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
