# Generated by Django 5.2.1 on 2025-06-16 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
